### ISSUE TITLE
Metadata error

### ISSUE THREAD

**Issue by sedjro** [aertslab/SCope#155]
I got an error with the latest release. Do I have to change the  building of the loom file ?

Here is the error:

```
Running SCope Server in development mode...
Starting XServer on port 55852...
{"msg": {"origin": "PServer", "value": "SIGSTART"}}
Starting DataFileHandler...
Starting LoomFileHandler...
{"msg": {"origin": "GServer", "value": "SIGSTART"}}
Debug: loading the loom file from /home/luna.kuleuven.be/u0118340/.local/share/SCope/my-looms/Leuven_noneutrophils_done-on-180508_new_tsne_scopeloom.loom...
New .loom created.
ERROR:root:Exception calling application: must be str, not int
Traceback (most recent call last):
  File "/home/luna.kuleuven.be/u0118340/.conda/envs/envs/lib/python3.6/site-packages/grpcio-1.12.0-py3.6-linux-x86_64.egg/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/data/scope/SCope/opt/scopeserver/dataserver/modules/gserver/GServer.py", line 426, in getMyLooms
    file_meta = loom.get_file_metadata()
  File "/data/scope/SCope/opt/scopeserver/utils/Loom.py", line 136, in get_file_metadata
    meta = { k: v for d in md for k, v in d.items() }
  File "/data/scope/SCope/opt/scopeserver/utils/Loom.py", line 136, in <dictcomp>
    meta = { k: v for d in md for k, v in d.items() }
  File "/data/scope/SCope/opt/scopeserver/utils/Loom.py", line 131, in loom_attr_exists
    raise ValueError("Invalid margin value: "+ margin)
TypeError: must be str, not int
```

**Comment by mase5** [comment]
Fixed in 2d7b5cf712550271a7e43d2d352d62dbe0ad7d7f.
