### ISSUE TITLE
Metadata error #155

### ISSUE THREAD

**Issue by sedjro** [aertslab/SCope#156]
New error:
``` 
Running SCope Server in development mode...
Starting XServer on port 55852...
{"msg": {"origin": "PServer", "value": "SIGSTART"}}
Starting DataFileHandler...
Starting LoomFileHandler...
{"msg": {"origin": "GServer", "value": "SIGSTART"}}
Removing UUID: 42e0f50f-05db-40ca-ac63-06b28a9010bc
Removing UUID: c1ac51c9-c580-4f71-afd2-58afe52dd198
Removing UUID: d9e2448c-aa7d-43a8-a11f-46d203477b10
Debug: loading the loom file from /home/luna.kuleuven.be/u0118340/.local/share/SCope/my-looms/Leuven_noneutrophils_done-on-180508_new_tsne_scopeloom.loom...
New .loom created.
ERROR:root:Exception calling application: Invalid margin value: 2
Traceback (most recent call last):
  File "/home/luna.kuleuven.be/u0118340/.conda/envs/envs/lib/python3.6/site-packages/grpcio-1.12.0-py3.6-linux-x86_64.egg/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/data/scope/SCope/opt/scopeserver/dataserver/modules/gserver/GServer.py", line 426, in getMyLooms
    file_meta = loom.get_file_metadata()
  File "/data/scope/SCope/opt/scopeserver/utils/Loom.py", line 136, in get_file_metadata
    meta = { k: v for d in md for k, v in d.items() }
  File "/data/scope/SCope/opt/scopeserver/utils/Loom.py", line 136, in <dictcomp>
    meta = { k: v for d in md for k, v in d.items() }
  File "/data/scope/SCope/opt/scopeserver/utils/Loom.py", line 131, in loom_attr_exists
    raise ValueError("Invalid margin value: {0}".format(margin))
ValueError: Invalid margin value: 2
```

**Comment by mase5** [comment]
Fixed in e9d5d0d0b56967f100d9cb39eae67569f086a914.
