### ISSUE TITLE
scope-server fails due to loompy version conflict

### ISSUE THREAD

**Issue by merges** [aertslab/SCope#170]
I'm having trouble getting `scope-server` running. It looks like there is a version/requirements mismatch between for the package `loompy` between `scope-server` and `pyscenic`. I'm on Mac OS X and followed the instructions in the README, doing the following:

 1. Installed Miniconda3 (current version).
 2. Created a fresh `scope` environment with Python 3.6.
 3. Checked out the SCope repo.
 4. Ran `npm install` (successfully)
 5. Ran `scope-server` and saw the result below.

I'd really appreciate any advice on how to proceed. Thanks!

```
(scope) <username-omitted>$ scope-server

Traceback (most recent call last):
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (loompy 2.0.14 (/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/loompy-2.0.14-py3.6.egg), Requirement.parse('loompy==2.0.2'), {'pyscenic'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<username-omitted>/miniconda3/envs/scope/bin/scope-server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (loompy 2.0.14 (/Users/<username-omitted>/miniconda3/envs/scope/lib/python3.6/site-packages/loompy-2.0.14-py3.6.egg), Requirement.parse('loompy==2.0.2'), {'pyscenic'})
```

**Comment by mase5** [comment]
Indeed the SCope Server setup.py file requires at least version 2.0.2. This is causing the bug. Up to now, the current versions of SCope are constrained to use `loompy` version 2.0.2 since `pyscenic` is also constrained to use this version to be `python` version 3.5 compatible. In the upcoming versions, we will definitely make SCope compatible version loompy latest versions.
For now I fixed the bug by forcing the requirements in setup.py to use `loompy` version 2.0.0 (see commit 3bca076b0f52497f1ca869de5e388d24a2a85b47).

**Comment by merges** [comment]
Thank you for the hotfix; this did indeed work.
