### ISSUE TITLE
scope-server won't run because of protobuf issue

### ISSUE THREAD

**Issue by merges** [aertslab/SCope#171]
After successfully starting `scope-server`, it subsequently encounters the following issue. A quick search indicates that something may have changed between `protobufjs` 5 and 6, but I'm not sure what the relevance is to the setup `scope-server` uses: https://github.com/googleapis/nodejs-bigtable/issues/44

```
Starting XServer on port 55852...
/Users/<username_omitted>/<path_omitted>/SCope/opt/scopeserver/bindserver/server.js:12
gbBuilder = protobuf.loadProtoFile(path.join(__dirname,'grpc-bus.proto'));
                     ^

TypeError: protobuf.loadProtoFile is not a function
    at Object.<anonymous> (/Users/<username_omitted>/<path_omitted>/SCope/opt/scopeserver/bindserver/server.js:12:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

**Comment by mase5** [comment]
This is a problem related to the Bind Server which makes the connection between SCope Data Server and SCope client. Currently, the Bind Server does not support Protobuf JS v6. 
Can you try to to force to install Protobuf JS v5 for the Bind Server: 
```
cd opt/scopeserver/bindserver
npm install protobufjs@5.0.2
```
Then rerun SCope and the app should start errorless

**Comment by merges** [comment]
Thank you! This fix worked and enabled `scope-server` to run. Might this be worth a note in the `README`?

**Comment by mase5** [comment]
Yes could worth it; but how come that ProtobufJS v6 vas been installed in `opt/scopeserver/bindserver` ? Did you follow the normal installation procedure?

**Comment by mase5** [comment]
I tried a fresh reinstallation of SCope on my local computer (Ubuntu 16.0.4):
```
git clone https://github.com/aertslab/SCope.git
cd SCope
conda create -n scope-test python=3.6.2
source activate scope-test
npm install
```
Unfortunately, running `scope-server` did not reproduced your error. ProtobufJS v5 (and not v6) was correctly installed in `opt/scopeserver/bindserver` folder. I still don't get how ProtobufJS v6 was installed there when you installed SCope.
