### ISSUE TITLE
Publicly available loom files: dtype object is not allowed

### ISSUE THREAD

**Issue by davek44** [aertslab/SCope#185]
The loom files on the SCope website cannot be read into loompy with the latest version 0.2.16. See below.

```
>>> import loompy
>>> loompy.__version__
'2.0.16'
>>> lc = loompy.connect('Linnarsson_Mouse_Brain_3k.loom')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drk/code/loompy/loompy/loompy.py", line 1140, in connect
    return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)
  File "/home/drk/code/loompy/loompy/loompy.py", line 84, in __init__
    raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
ValueError: Row attribute 'Gene' dtype object is not allowed
...
```

In contrast, they do connect with 0.2.10.

```
>>> import loompy
>>> loompy.__version__
'2.0.10'
>>> lc = loompy.connect('Linnarsson_Mouse_Brain_3k.loom')
>>> lc
<loompy.loompy.LoomConnection object at 0x105e85048>

```

**Comment by MaybeJustJames** [comment]
@KrisDavie can this be closed?
