### ISSUE TITLE
unable to start scope client from a non-git repository

### ISSUE THREAD

**Issue by mfiers** [aertslab/SCope#88]
it seems that if I install from the master tarbal, I can install the client, but not start the client.

It does work if I run from a checked out git repository

```
:~/scope/SCope-master/scope-client$ npm run dev                                  
                                                                                                    
> scope-client@0.0.6 dev /home/mark_fiers_42/scope/SCope-master/scope-client  r         u     b     > cross-env NODE_ENV=development webpack-dev-server --hot                                           
                                                                           w  r         u     b     fatal: Not a git repository (or any of the parent directories): .git                                
child_process.js:644                                                                                
    throw err;                                                                                      
    ^                                       
                                                
Error: Command failed: git rev-parse --short=7 HEAD                                                 fatal: Not a git repository (or any of the parent directories): .git
                                         
    at checkExecSyncError (child_process.js:601:13)                                                 
    at Object.execSync (child_process.js:641:13)                                                    
    at WebpackGitHash.getSkipHash (/home/mark_fiers_42/scope/SCope-master/scope-client/node_modules/
webpack-git-hash/index.js:111:32)                                                                       at new WebpackGitHash (/home/mark_fiers_42/scope/SCope-master/scope-client/node_modules/webpack-
git-hash/index.js:39:26)                             
    at Object.<anonymous> (/home/mark_fiers_42/scope/SCope-master/scope-client/webpack.config.js:40:
9)                                                
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)                                                                   at tryModuleLoad (module.js:505:12)              
    at Function.Module._load (module.js:497:3)                     
npm ERR! code ELIFECYCLE
npm ERR! errno 1                                                                                    
npm ERR! scope-client@0.0.6 dev: `cross-env NODE_ENV=development webpack-dev-server --hot`          npm ERR! Exit status 1                                                          
npm ERR!                                                                                            npm ERR! Failed at the scope-client@0.0.6 dev script.         
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                          
npm ERR! A complete log of this run can be found in:                  
npm ERR!     /home/mark_fiers_42/.npm/_logs/2018-03-13T15_35_00_277Z-debug.log    
```

**Comment by KrisDavie** [comment]
Solved by running `npm run build` and then hosting the index.html files via a webserver
